"""add remaining memory tables

Revision ID: e82898730309
Revises: a2afbfcc6a34
Create Date: 2026-06-30 17:41:28.496915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e82898730309'
down_revision: Union[str, Sequence[str], None] = 'a2afbfcc6a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_memory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('learned_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_execution', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instruction_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('average_execution_time', sa.Float(), nullable=False),
    sa.Column('average_api_calls', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('optimized_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entrypoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_versions')
    op.drop_table('learning_metrics')
    op.drop_table('knowledge_base')
    op.drop_table('execution_memory')
    # ### end Alembic commands ###
